"""Landing/banner domain: slug validation, banner ordering, CTA placement,
publication validation, and the public not-found policy.

Pure functions only — no I/O. `LandingPublicationService` (app/services)
composes these with repositories inside Prisma transactions.
"""

from app.domains.landings.accent_color import (
    DEFAULT_ACCENT_COLOR,
    AccentPalette,
    derive_accent_palette,
    normalize_accent_color,
)
from app.domains.landings.alt_text import (
    ALT_TEXT_MAX_LENGTH,
    ALT_TEXT_MIN_LENGTH,
    validate_alt_text,
)
from app.domains.landings.banner_ordering import (
    MAX_BANNERS_PER_LANDING,
    contiguous_indices,
    next_append_index,
    reorder,
    validate_can_add_banner,
)
from app.domains.landings.blocks import (
    ALLOWED_BLOCK_TYPES,
    BLOCK_BENEFITS,
    BLOCK_COD_ASSURANCE,
    BLOCK_FAQ,
    BLOCK_GUARANTEE,
    BLOCK_INCLUDED_BENEFITS,
    BLOCK_OFFER_PRICE,
    BLOCK_REVIEWS,
    MAX_BLOCKS_PER_LANDING,
    MAX_ORDER_INDEX,
    MAX_SLOT_INDEX,
    slot_labels,
    validate_block_config,
    validate_block_type,
    validate_can_add_block,
    validate_order_index,
    validate_slot_index,
)
from app.domains.landings.cta_background import (
    SOURCE_ABOVE,
    SOURCE_BELOW,
    SOURCE_BLEND,
    SOURCE_FALLBACK,
    BannerEdges,
    CtaBandBackground,
    compute_cta_backgrounds,
)
from app.domains.landings.cta_band_style import (
    ALLOWED_CTA_BAND_STYLES,
    CTA_BAND_STYLE_GRADIENT,
    CTA_BAND_STYLE_SOLID,
    validate_cta_band_style,
)
from app.domains.landings.cta_placement import (
    ALLOWED_CTA_MODES,
    CTA_MODE_AFTER_EVERY,
    CTA_MODE_EVERY_N,
    CTA_MODE_FIXED_POSITIONS,
    CtaConfig,
    compute_cta_positions,
    validate_cta_config,
)
from app.domains.landings.cta_text_overrides import (
    OVERRIDE_TEXT_MAX,
    resolve_cta_text,
    validate_cta_text_overrides,
)
from app.domains.landings.errors import (
    BannerLimitExceededError,
    BannerNotFoundError,
    DuplicateSlugError,
    LandingNotFoundError,
    LandingValidationError,
    PublicationValidationError,
)
from app.domains.landings.form_presentation import (
    ALLOWED_FORM_PRESENTATIONS,
    FORM_PRESENTATION_INLINE,
    FORM_PRESENTATION_MODAL,
    validate_form_presentation,
)
from app.domains.landings.offers import (
    DISCOUNTABLE_MIN_QUANTITY,
    LABEL_MAX,
    MAX_DISCOUNT_PERCENT,
    MAX_OFFER_COUNT,
    MIN_DISCOUNT_PERCENT,
    MIN_OFFER_COUNT,
    SUBLABEL_MAX,
    LandingOffer,
    OfferPricing,
    default_offers,
    find_offer,
    parse_stored_offers,
    resolve_offer_pricing,
    validate_offer_count,
    validate_offers,
)
from app.domains.landings.slug import validate_slug_format

__all__ = [
    "LandingValidationError",
    "DuplicateSlugError",
    "LandingNotFoundError",
    "BannerNotFoundError",
    "BannerLimitExceededError",
    "PublicationValidationError",
    "validate_slug_format",
    "ALT_TEXT_MIN_LENGTH",
    "ALT_TEXT_MAX_LENGTH",
    "validate_alt_text",
    "FORM_PRESENTATION_INLINE",
    "FORM_PRESENTATION_MODAL",
    "ALLOWED_FORM_PRESENTATIONS",
    "validate_form_presentation",
    "MAX_BANNERS_PER_LANDING",
    "validate_can_add_banner",
    "next_append_index",
    "reorder",
    "contiguous_indices",
    "CTA_MODE_AFTER_EVERY",
    "CTA_MODE_EVERY_N",
    "CTA_MODE_FIXED_POSITIONS",
    "ALLOWED_CTA_MODES",
    "CtaConfig",
    "validate_cta_config",
    "compute_cta_positions",
    "OVERRIDE_TEXT_MAX",
    "validate_cta_text_overrides",
    "resolve_cta_text",
    "BannerEdges",
    "CtaBandBackground",
    "compute_cta_backgrounds",
    "SOURCE_BLEND",
    "SOURCE_ABOVE",
    "SOURCE_BELOW",
    "SOURCE_FALLBACK",
    "CTA_BAND_STYLE_GRADIENT",
    "CTA_BAND_STYLE_SOLID",
    "ALLOWED_CTA_BAND_STYLES",
    "validate_cta_band_style",
    "BLOCK_COD_ASSURANCE",
    "BLOCK_BENEFITS",
    "BLOCK_OFFER_PRICE",
    "BLOCK_INCLUDED_BENEFITS",
    "BLOCK_REVIEWS",
    "BLOCK_FAQ",
    "BLOCK_GUARANTEE",
    "ALLOWED_BLOCK_TYPES",
    "MAX_BLOCKS_PER_LANDING",
    "MAX_SLOT_INDEX",
    "MAX_ORDER_INDEX",
    "validate_block_type",
    "validate_block_config",
    "validate_slot_index",
    "validate_order_index",
    "validate_can_add_block",
    "slot_labels",
    "DEFAULT_ACCENT_COLOR",
    "AccentPalette",
    "normalize_accent_color",
    "derive_accent_palette",
    "MIN_OFFER_COUNT",
    "MAX_OFFER_COUNT",
    "LABEL_MAX",
    "SUBLABEL_MAX",
    "MIN_DISCOUNT_PERCENT",
    "MAX_DISCOUNT_PERCENT",
    "DISCOUNTABLE_MIN_QUANTITY",
    "LandingOffer",
    "OfferPricing",
    "validate_offer_count",
    "validate_offers",
    "parse_stored_offers",
    "default_offers",
    "resolve_offer_pricing",
    "find_offer",
]
