CREATE TABLE "store_settings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "store_name" VARCHAR(100) NOT NULL DEFAULT 'Mi Tienda',
    "legal_name" VARCHAR(160) NOT NULL DEFAULT '',
    "primary_color" VARCHAR(7) NOT NULL DEFAULT '#30503b',
    "logo_url" TEXT,
    "logo_object_key" TEXT,
    "favicon_url" TEXT,
    "favicon_object_key" TEXT,
    "homepage_image_url" TEXT,
    "homepage_image_object_key" TEXT,
    "whatsapp_number" VARCHAR(16) NOT NULL DEFAULT '',
    "whatsapp_message" VARCHAR(500) NOT NULL DEFAULT 'Hola, me gustaría conocer más sobre tus productos.',
    "support_email" VARCHAR(254) NOT NULL DEFAULT '',
    "home_eyebrow" VARCHAR(100) NOT NULL DEFAULT 'Selección especial',
    "home_headline" VARCHAR(180) NOT NULL DEFAULT 'Productos seleccionados para ti',
    "home_description" VARCHAR(500) NOT NULL DEFAULT 'Compra con confianza y recibe tu pedido en casa.',
    "home_cta_label" VARCHAR(80) NOT NULL DEFAULT 'Escribir por WhatsApp',
    "trust_items" JSONB NOT NULL DEFAULT '[]',
    "secondary_headline" VARCHAR(180) NOT NULL DEFAULT '¿Tienes preguntas?',
    "secondary_description" VARCHAR(500) NOT NULL DEFAULT 'Estamos aquí para ayudarte.',
    "footer_text" VARCHAR(240) NOT NULL DEFAULT 'Compra segura con garantía de calidad',
    "seo_title" VARCHAR(70) NOT NULL DEFAULT 'Mi Tienda',
    "seo_description" VARCHAR(180) NOT NULL DEFAULT '',
    "gtm_container_id" VARCHAR(20) NOT NULL DEFAULT '',
    "meta_pixel_id" VARCHAR(30) NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "store_settings_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "store_settings_singleton" CHECK ("id" = 1),
    CONSTRAINT "store_settings_primary_color" CHECK ("primary_color" ~ '^#[0-9a-fA-F]{6}$')
);
