"""Argon2id password hashing (Requirement 7.6).

Administrator passwords are hashed with Argon2id (memory-hard) using a
unique per-hash salt generated by the library — plaintext is never stored
or logged, and the hash is never reversible.
"""

from __future__ import annotations

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError

_hasher = PasswordHasher()


def hash_password(plaintext_password: str) -> str:
    """Hash a plaintext password with Argon2id and a unique random salt."""
    return _hasher.hash(plaintext_password)


def verify_password(stored_hash: str, plaintext_password: str) -> bool:
    """Return True iff `plaintext_password` matches `stored_hash`.

    Never raises on a mismatch; any Argon2 verification failure (wrong
    password, malformed/foreign hash) is treated as "does not match" so
    callers can return a single generic authentication error (Requirement
    7.2) regardless of which check failed.
    """
    try:
        return _hasher.verify(stored_hash, plaintext_password)
    except VerifyMismatchError:
        return False
    except Exception:
        # Malformed hash, unsupported parameters, etc. — never surfaced to
        # the caller as anything other than "credentials did not match".
        return False
